name: Kwiki-ForeignLinkGlyphs
version: 0.01
abstract: display an image after links that aren't local
author: Ian Langworth <langworth.com>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  Kwiki::Formatter: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
